// LLM Prompt Generator
// Assembles PROMPT.md from static sections + selected component source code

import { generateStaticPromptSections } from "./llm-prompt-sections"

export interface ComponentFile {
  filename: string
  content: string
}

// Generate the component reference section - just list files, don't embed source
function generateComponentReference(components: ComponentFile[]): string {
  if (components.length === 0) return ""

  // Group components by first letter for easier scanning
  const sortedComponents = [...components].sort((a, b) => 
    a.filename.localeCompare(b.filename)
  )

  let output = `
---

# Included Components

This export contains **${components.length} components**. Their source files are in \`components/ui/\`.

| Component | File |
|-----------|------|
`

  for (const comp of sortedComponents) {
    const componentName = comp.filename
      .replace(".tsx", "")
      .split("-")
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ")

    output += `| ${componentName} | \`${comp.filename}\` |\n`
  }

  output += `

## Reading Component Source

When implementing or extending components:

1. **Read the source file** from \`components/ui/\` - it contains the complete implementation
2. **Follow the same patterns** - use CVA for variants, cn() for class merging, forwardRef for refs
3. **Check imports** - component dependencies are visible at the top of each file

The component files are the single source of truth. This guide provides the principles; the files provide the implementation.
`

  return output
}

// Generate the full PROMPT.md content
export function generateLLMPrompt(
  components: ComponentFile[],
  options: {
    githubUrl: string
    accentColor: string
    accentHSL: string
  }
): string {
  const staticSections = generateStaticPromptSections(options.githubUrl)
  const componentReference = generateComponentReference(components)

  const accentSection = `
---

# Current Theme Configuration

This export is configured with the following accent color:

- **Accent:** ${options.accentColor}
- **HSL Value:** ${options.accentHSL}

The \`globals.css\` file has been pre-configured with this as the default \`--primary\` color.
`

  const closingSection = `
---

# Quick Start

1. Copy the \`components/ui/\` folder to your project's \`src/components/ui/\`
2. Copy \`lib/utils.ts\` to your \`src/lib/\`
3. Merge \`styles/globals.css\` with your global styles
4. Merge \`tailwind.config.js\` with your Tailwind config
5. Install dependencies from \`package.json\`

You're ready to use CarbonCN components!

---

*Generated by CarbonCN Design System Export*
*For updates and more components, visit: ${options.githubUrl}*
`

  return [
    staticSections,
    accentSection,
    componentReference,
    closingSection,
  ].join("\n")
}

